ALTER TABLE "Sale" ADD COLUMN IF NOT EXISTS "origen" TEXT;
ALTER TABLE "Sale" ADD COLUMN IF NOT EXISTS "envioExterior" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Sale" ADD COLUMN IF NOT EXISTS "quienRecoge" TEXT;
ALTER TABLE "Sale" ADD COLUMN IF NOT EXISTS "telefono" TEXT;