DO $$ BEGIN
  CREATE TYPE "SaleStatus" AS ENUM ('PENDIENTE', 'PAGADO');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE "Sale" ADD COLUMN IF NOT EXISTS "status" "SaleStatus" NOT NULL DEFAULT 'PENDIENTE';
ALTER TABLE "Sale" ADD COLUMN IF NOT EXISTS "nitName" TEXT;